// Missions merged into achievements (daily/weekly recurring)
export const SEED_MISSION_ACHIEVEMENTS = [
  // ── Daily Easy ──
  { key:'daily_1_lesson', name:'Complete 1 lição hoje', description:'"A palavra de Deus é viva e eficaz." (Hb 4:12)', icon_emoji:'📖', trigger:{type:'lesson_count' as const,value:1}, rarity:'common' as const, cycle:'daily' as const, difficulty:'easy' as const, pf_reward:10, mana_reward:5, verse_reference:'Hebreus 4:12', is_active:true, is_premium:false, sort_order:100 },
  { key:'daily_2_lessons', name:'Complete 2 lições hoje', description:'Dois passos a mais na sua jornada de fé!', icon_emoji:'📚', trigger:{type:'lesson_count' as const,value:2}, rarity:'common' as const, cycle:'daily' as const, difficulty:'easy' as const, pf_reward:20, mana_reward:8, is_active:true, is_premium:false, sort_order:101 },
  { key:'daily_20xp', name:'Ganhe 20 PF hoje', description:'"Tudo posso naquele que me fortalece." (Fp 4:13)', icon_emoji:'✨', trigger:{type:'pf_earn' as const,value:20}, rarity:'common' as const, cycle:'daily' as const, difficulty:'easy' as const, pf_reward:15, mana_reward:5, verse_reference:'Filipenses 4:13', is_active:true, is_premium:false, sort_order:102 },
  { key:'daily_streak', name:'Mantenha seu streak ativo hoje', description:'"Seja constante na oração." (Rm 12:12)', icon_emoji:'🔥', trigger:{type:'streak_maintain' as const,value:1}, rarity:'common' as const, cycle:'daily' as const, difficulty:'easy' as const, pf_reward:15, mana_reward:5, verse_reference:'Romanos 12:12', is_active:true, is_premium:false, sort_order:103 },
  // ── Daily Medium ──
  { key:'daily_3_lessons', name:'Complete 3 lições hoje', description:'Três lições — você está crescendo em fé!', icon_emoji:'🌟', trigger:{type:'lesson_count' as const,value:3}, rarity:'common' as const, cycle:'daily' as const, difficulty:'medium' as const, pf_reward:35, mana_reward:12, is_active:true, is_premium:false, sort_order:110 },
  { key:'daily_perfect', name:'Acerte tudo em 1 lição', description:'"Aplica o teu coração ao ensino." (Pv 23:12)', icon_emoji:'💯', trigger:{type:'perfect_lesson' as const,value:1}, rarity:'common' as const, cycle:'daily' as const, difficulty:'medium' as const, pf_reward:30, mana_reward:10, verse_reference:'Provérbios 23:12', is_active:true, is_premium:false, sort_order:111 },
  { key:'daily_50xp', name:'Ganhe 50 PF hoje', description:'Uma conquista sólida para o seu dia!', icon_emoji:'⚡', trigger:{type:'pf_earn' as const,value:50}, rarity:'common' as const, cycle:'daily' as const, difficulty:'medium' as const, pf_reward:25, mana_reward:8, is_active:true, is_premium:false, sort_order:112 },
  { key:'daily_trail_2', name:'Avance 2 lições em uma trilha', description:'"Firme os olhos em Jesus." (Hb 12:2)', icon_emoji:'🛤️', trigger:{type:'trail_progress' as const,value:2}, rarity:'common' as const, cycle:'daily' as const, difficulty:'medium' as const, pf_reward:30, mana_reward:10, verse_reference:'Hebreus 12:2', is_active:true, is_premium:false, sort_order:113 },
  // ── Daily Hard ──
  { key:'daily_5_lessons', name:'Complete 5 lições hoje', description:'Cinco lições em um dia — Apóstolo da disciplina!', icon_emoji:'🏆', trigger:{type:'lesson_count' as const,value:5}, rarity:'rare' as const, cycle:'daily' as const, difficulty:'hard' as const, pf_reward:60, mana_reward:20, is_active:true, is_premium:false, sort_order:120 },
  { key:'daily_3_perfect', name:'Acerte tudo em 3 lições seguidas', description:'"Feliz o homem que acha a sabedoria." (Pv 3:13)', icon_emoji:'👑', trigger:{type:'perfect_lesson' as const,value:3}, rarity:'rare' as const, cycle:'daily' as const, difficulty:'hard' as const, pf_reward:70, mana_reward:25, verse_reference:'Provérbios 3:13', is_active:true, is_premium:true, sort_order:121 },
  { key:'daily_100xp', name:'Ganhe 100 PF hoje', description:'Centena de PF em um único dia — extraordinário!', icon_emoji:'💎', trigger:{type:'pf_earn' as const,value:100}, rarity:'rare' as const, cycle:'daily' as const, difficulty:'hard' as const, pf_reward:80, mana_reward:30, is_active:true, is_premium:false, sort_order:122 },
  // ── Weekly ──
  { key:'weekly_5_lessons', name:'Complete 5 lições nesta semana', description:'"Os que esperam no Senhor renovarão as forças." (Is 40:31)', icon_emoji:'📅', trigger:{type:'lesson_count' as const,value:5}, rarity:'common' as const, cycle:'weekly' as const, difficulty:'easy' as const, pf_reward:40, mana_reward:15, verse_reference:'Isaías 40:31', is_active:true, is_premium:false, sort_order:130 },
  { key:'weekly_5_streak', name:'Mantenha 5 dias de streak esta semana', description:'Cinco dias de devoção na presença de Deus!', icon_emoji:'🕯️', trigger:{type:'streak_maintain' as const,value:5}, rarity:'common' as const, cycle:'weekly' as const, difficulty:'easy' as const, pf_reward:50, mana_reward:18, is_active:true, is_premium:false, sort_order:131 },
  { key:'weekly_10_lessons', name:'Complete 10 lições nesta semana', description:'Dez passos na sua jornada. Você está crescendo!', icon_emoji:'⭐', trigger:{type:'lesson_count' as const,value:10}, rarity:'common' as const, cycle:'weekly' as const, difficulty:'medium' as const, pf_reward:80, mana_reward:25, is_active:true, is_premium:false, sort_order:140 },
  { key:'weekly_study', name:'Conclua 1 estudo bíblico esta semana', description:'Um mergulho profundo na Palavra!', icon_emoji:'🔍', trigger:{type:'study_complete' as const,value:1}, rarity:'common' as const, cycle:'weekly' as const, difficulty:'medium' as const, pf_reward:100, mana_reward:35, is_active:true, is_premium:false, sort_order:141 },
  { key:'weekly_7_streak', name:'Semana completa de streak (7 dias)', description:'"Nunca se apague o vosso fervor." (Rm 12:11)', icon_emoji:'🔥', trigger:{type:'streak_maintain' as const,value:7}, rarity:'rare' as const, cycle:'weekly' as const, difficulty:'medium' as const, pf_reward:120, mana_reward:40, verse_reference:'Romanos 12:11', is_active:true, is_premium:false, sort_order:142 },
  { key:'weekly_20_lessons', name:'Complete 20 lições nesta semana', description:'Vinte lições — entre os mais dedicados!', icon_emoji:'🏅', trigger:{type:'lesson_count' as const,value:20}, rarity:'rare' as const, cycle:'weekly' as const, difficulty:'hard' as const, pf_reward:180, mana_reward:60, is_active:true, is_premium:false, sort_order:150 },
  { key:'weekly_invite', name:'Convide 1 amigo esta semana', description:'"Como são formosos os pés do que anuncia." (Rm 10:15)', icon_emoji:'📯', trigger:{type:'invite_count' as const,value:1}, rarity:'rare' as const, cycle:'weekly' as const, difficulty:'hard' as const, pf_reward:150, mana_reward:50, verse_reference:'Romanos 10:15', is_active:true, is_premium:false, sort_order:151 },
];

// Original one-time achievements
export const SEED_ACHIEVEMENTS = [
  { key:'first_lesson', name:'Primeira Pedra', description:'Complete sua primeira lição', verse_reference:'Isaías 28:16', verse_text:'Eis que ponho em Sião uma pedra angular, escolhida e preciosa.', icon_emoji:'🗿', trigger:{type:'lesson_count' as const,value:1}, rarity:'common' as const, pf_reward:20, mana_reward:5, is_active:true, sort_order:1 },
  { key:'seven_day_streak', name:'Sete Dias de Criação', description:'Mantenha 7 dias de devoção seguidos', verse_reference:'Gênesis 1', verse_text:'E viu Deus tudo quanto tinha feito, e eis que era muito bom.', icon_emoji:'🕯️', trigger:{type:'streak_days' as const,value:7}, rarity:'common' as const, pf_reward:50, mana_reward:10, is_active:true, sort_order:2 },
  { key:'first_trail_complete', name:'O Museu das Maravilhas', description:'Conclua sua primeira trilha completa', verse_reference:'1 Crônicas 16:24', verse_text:'Anunciai as suas maravilhas entre todos os povos.', icon_emoji:'🏛️', trigger:{type:'trail_complete' as const,value:1}, rarity:'common' as const, pf_reward:100, mana_reward:20, is_active:true, sort_order:3 },
  { key:'forty_day_streak', name:'40 Dias no Deserto', description:'Mantenha 40 dias de devoção seguidos', verse_reference:'Mateus 4:2', verse_text:'E, depois de jejuar quarenta dias e quarenta noites, teve fome.', icon_emoji:'🏜️', trigger:{type:'streak_days' as const,value:40}, rarity:'rare' as const, pf_reward:300, mana_reward:50, is_active:true, sort_order:4 },
  { key:'league_champion', name:'Coroa de Vitória', description:'Termine em 1° lugar em uma liga semanal', verse_reference:'2 Timóteo 4:7-8', verse_text:'Pelejei o bom combate, acabei a carreira, guardei a fé.', icon_emoji:'👑', trigger:{type:'league_rank' as const,value:1}, rarity:'rare' as const, pf_reward:200, mana_reward:40, is_active:true, sort_order:5 },
  { key:'perfect_lesson', name:'Sem Pecado Neste Quiz', description:'Complete uma lição com 100% de acertos', verse_reference:'1 João 2:1', verse_text:'Filhinhos meus, escrevo-vos estas coisas para que não pequeis.', icon_emoji:'✨', trigger:{type:'perfect_lesson' as const,value:1}, rarity:'common' as const, pf_reward:25, mana_reward:5, is_active:true, sort_order:6 },
  { key:'ten_lessons', name:'Dez Palavras', description:'Complete 10 lições', verse_reference:'Êxodo 20', verse_text:'Então Deus pronunciou todas estas palavras.', icon_emoji:'📖', trigger:{type:'lesson_count' as const,value:10}, rarity:'common' as const, pf_reward:30, mana_reward:8, is_active:true, sort_order:7 },
  { key:'fifty_lessons', name:'O Jubileu', description:'Complete 50 lições', verse_reference:'Levítico 25:10', verse_text:'Santificareis o ano quinquagésimo e proclamareis liberdade na terra.', icon_emoji:'🎺', trigger:{type:'lesson_count' as const,value:50}, rarity:'rare' as const, pf_reward:200, mana_reward:40, is_active:true, sort_order:8 },
  { key:'hundred_lessons', name:'O Centurião', description:'Complete 100 lições', verse_reference:'Mateus 8:10', verse_text:'Em verdade vos digo que nem em Israel achei fé tão grande.', icon_emoji:'⚔️', trigger:{type:'lesson_count' as const,value:100}, rarity:'epic' as const, pf_reward:500, mana_reward:100, is_active:true, sort_order:9 },
  { key:'level_10', name:'Aprendiz Confirmado', description:'Alcance o nível 10', verse_reference:'Lucas 2:52', verse_text:'E Jesus crescia em sabedoria, em estatura e em graça.', icon_emoji:'⭐', trigger:{type:'level' as const,value:10}, rarity:'common' as const, pf_reward:100, mana_reward:20, is_active:true, sort_order:10 },
  { key:'ninety_day_streak', name:'Tempo de Colheita', description:'Mantenha 90 dias de devoção seguidos', verse_reference:'Gálatas 6:9', verse_text:'Não nos cansemos de fazer o bem, pois a seu tempo ceifaremos.', icon_emoji:'🌾', trigger:{type:'streak_days' as const,value:90}, rarity:'epic' as const, pf_reward:800, mana_reward:150, is_active:true, sort_order:11 },
  { key:'invite_5', name:'O Mensageiro Fiel', description:'Convide 5 amigos que se cadastram no app', verse_reference:'Romanos 10:15', verse_text:'Como são formosos os pés dos que anunciam o evangelho das coisas boas.', icon_emoji:'📯', trigger:{type:'invite_count' as const,value:5}, rarity:'rare' as const, pf_reward:150, mana_reward:30, is_active:true, sort_order:12 },
  { key:'wisdom_trail', name:'Aprendiz de Salomão', description:'Conclua a trilha de Sabedoria', verse_reference:'Provérbios 3:13', verse_text:'Feliz o homem que acha a sabedoria e obtém entendimento.', icon_emoji:'📜', trigger:{type:'trail_complete' as const,value:1}, rarity:'common' as const, pf_reward:80, mana_reward:15, is_active:true, sort_order:13 },
  { key:'diamond_league', name:'A Pedra Preciosa', description:'Alcance a Liga Diamante', verse_reference:'Ezequiel 28:13', verse_text:'Todo pedra preciosa era a tua coberta: o sárdio, o topázio e o diamante.', icon_emoji:'💎', trigger:{type:'league_rank' as const,value:1}, rarity:'epic' as const, pf_reward:1000, mana_reward:200, is_active:true, sort_order:14 },
  { key:'one_year_streak', name:'O Ano Sabático', description:'Mantenha 365 dias de devoção seguidos', verse_reference:'Êxodo 23:11', verse_text:'No sétimo ano deixarás a terra descansar e ficar em pousio.', icon_emoji:'🕎', trigger:{type:'streak_days' as const,value:365}, rarity:'epic' as const, pf_reward:5000, mana_reward:1000, is_active:true, sort_order:15 },
  { key:'xp_5000', name:'Tesouro Escondido', description:'Acumule 5.000 Pontos de Fé', verse_reference:'Mateus 13:44', verse_text:'O Reino dos Céus é semelhante a um tesouro escondido num campo.', icon_emoji:'💰', trigger:{type:'pf_total' as const,value:5000}, rarity:'rare' as const, pf_reward:250, mana_reward:50, is_active:true, sort_order:16 },
];
