export const SEED_CHARACTERS = [
  {
    name:               'Caleb',
    title:              'O Corajoso',
    biblical_reference: 'Números 13-14 | Josué 14',
    biblical_story:     'Caleb foi um dos doze espias enviados por Moisés a Canaã. Enquanto dez voltaram com medo, só Caleb e Josué disseram "Certamente podemos conquistá-la!" Décadas depois, aos 85 anos, ele ainda pedia a montanha mais difícil.',
    sprite_url:         'https://placehold.co/200x280/D4A017/white?text=CALEB',
    color_hex:          '#D4A017',
    rarity:             'common',
    is_sacred:          false,
    is_active:          true,
    sort_order:         1,
    unlock_condition:   { type: 'default' },
    dialogues: [
      { type: 'greeting',        text: 'Olá! Que bom te ver de volta à sua jornada de fé!' },
      { type: 'correct',         text: 'Isso aí! Você está crescendo na fé, assim como eu cresci no deserto!' },
      { type: 'wrong',           text: 'Não desanime! Mesmo eu errei algumas vezes no caminho para Canaã.' },
      { type: 'streak_warning',  text: 'Sua vela ainda está acesa — mas não deixe apagar! Faça sua lição hoje!' },
      { type: 'streak_broken',   text: 'A vela apagou... Mas cada amanhecer é uma nova chance. Vamos recomeçar!' },
      { type: 'level_up',        text: 'Subiu de nível! Como diz Josué 14:12 — Aqui estou, dá-me esta montanha!' },
      { type: 'lesson_complete', text: 'Lição concluída! Você está conquistando seu Canaã particular!' },
    ],
  },
  {
    name:               'Miriam',
    title:              'A Profetisa',
    biblical_reference: 'Êxodo 2 | Êxodo 15 | Números 12',
    biblical_story:     'Irmã de Moisés e Arão, Miriam foi chamada de profetisa nas Escrituras. Foi ela quem vigiou o bebê Moisés no Nilo e liderou as mulheres de Israel em cântico de louvor após a travessia do Mar Vermelho.',
    sprite_url:         'https://placehold.co/200x280/1ABC9C/white?text=MIRIAM',
    color_hex:          '#1ABC9C',
    rarity:             'common',
    is_sacred:          false,
    is_active:          true,
    sort_order:         2,
    unlock_condition:   { type: 'trail_complete', value: 'fundamentos-vida-de-jesus' },
    dialogues: [
      { type: 'greeting',        text: 'Bem-vindo! Toda jornada começa com um primeiro passo de fé.' },
      { type: 'correct',         text: 'Sim! "Cantai ao Senhor, porque gloriosamente triunfou!" Êxodo 15:21' },
      { type: 'wrong',           text: 'Mesmo Miriam teve momentos de falha. O importante é continuar!' },
      { type: 'lesson_complete', text: 'Hora de dançar de alegria, como fiz às margens do Mar Vermelho!' },
    ],
  },
  {
    name:               'Timóteo',
    title:              'O Discípulo Fiel',
    biblical_reference: 'Atos 16 | 1 Timóteo | 2 Timóteo',
    biblical_story:     'Jovem discípulo do apóstolo Paulo, Timóteo tornou-se um dos líderes mais importantes da Igreja primitiva. Paulo o chamou de "meu filho amado e fiel no Senhor" e o instruiu: "Ninguém te despreze pela tua mocidade".',
    sprite_url:         'https://placehold.co/200x280/3498DB/white?text=TIMOTEO',
    color_hex:          '#3498DB',
    rarity:             'common',
    is_sacred:          false,
    is_active:          true,
    sort_order:         3,
    unlock_condition:   { type: 'level', value: 5 },
    dialogues: [
      { type: 'greeting',      text: 'Olá! Assim como Paulo me ensinou, estou aqui para caminhar com você.' },
      { type: 'correct',       text: 'Excelente! "Procura apresentar-te a Deus aprovado." 2 Timóteo 2:15' },
      { type: 'lesson_start',  text: 'Vamos ao estudo! A Palavra é lâmpada para os nossos pés.' },
    ],
  },
  {
    name:               'Débora',
    title:              'A Juíza e Profetisa',
    biblical_reference: 'Juízes 4-5',
    biblical_story:     'Única mulher juíza de Israel, Débora governou com sabedoria e discernimento. Quando Baraque hesitou em ir à batalha, Débora foi. Sua vitória sobre Sísera está imortalizada no Cântico de Débora.',
    sprite_url:         'https://placehold.co/200x280/E91E8C/white?text=DEBORA',
    color_hex:          '#E91E8C',
    rarity:             'uncommon',
    is_sacred:          false,
    is_active:          true,
    sort_order:         4,
    unlock_condition:   { type: 'level', value: 10 },
    dialogues: [
      { type: 'greeting', text: 'Que bom que chegou! Toda batalha começa com discernimento.' },
      { type: 'correct',  text: 'Isso! Uma mente treinada na Palavra não erra com facilidade.' },
      { type: 'level_up', text: 'Subiu de nível! Você está crescendo em sabedoria e força!' },
    ],
  },
  {
    name:               'Salomão',
    title:              'O Rei Sábio',
    biblical_reference: '1 Reis 3-11 | Provérbios | Eclesiastes',
    biblical_story:     'Filho de Davi, Salomão pediu a Deus não riqueza nem poder, mas sabedoria. E Deus lhe deu todas as coisas. Construiu o Templo em Jerusalém e escreveu Provérbios, Eclesiastes e Cantares.',
    sprite_url:         'https://placehold.co/200x280/F39C12/white?text=SALOMAO',
    color_hex:          '#F39C12',
    rarity:             'uncommon',
    is_sacred:          false,
    is_active:          true,
    sort_order:         5,
    unlock_condition:   { type: 'level', value: 20 },
    dialogues: [
      { type: 'greeting', text: 'Bem-vindo ao estudo. A sabedoria começa pelo temor ao Senhor.' },
      { type: 'correct',  text: 'Sábio! "Feliz o homem que acha a sabedoria." Provérbios 3:13' },
      { type: 'wrong',    text: 'Errei muito também. O sábio aprende com os erros. Continue!' },
    ],
  },
  {
    name:               'Ester',
    title:              'A Rainha Corajosa',
    biblical_reference: 'Livro de Ester',
    biblical_story:     'Uma jovem judia órfã que se tornou rainha da Pérsia. Quando seu povo foi ameaçado de extermínio, Ester arriscou a própria vida ao ir ao rei sem ser convocada. "Se perecer, perecerei." Sua coragem salvou uma nação.',
    sprite_url:         'https://placehold.co/200x280/9B59B6/white?text=ESTER',
    color_hex:          '#9B59B6',
    rarity:             'rare',
    is_sacred:          false,
    is_active:          true,
    sort_order:         6,
    unlock_condition:   { type: 'streak', value: 30 },
    dialogues: [
      { type: 'greeting',       text: 'Quem sabe se não chegaste ao teu lugar para um momento como este?' },
      { type: 'correct',        text: 'Exatamente! A coragem e o conhecimento andam juntos.' },
      { type: 'streak_warning', text: 'Não desista agora — você está tão perto de algo grandioso!' },
    ],
  },
  {
    name:               'Elias',
    title:              'O Profeta de Fogo',
    biblical_reference: '1 Reis 17-21 | 2 Reis 2',
    biblical_story:     'O mais dramático dos profetas. Elias fechou os céus por três anos, confrontou 450 profetas de Baal no Monte Carmelo, fugiu para o deserto em depressão e foi arrebatado ao céu num carro de fogo.',
    sprite_url:         'https://placehold.co/200x280/E74C3C/white?text=ELIAS',
    color_hex:          '#E74C3C',
    rarity:             'rare',
    is_sacred:          false,
    is_active:          true,
    sort_order:         7,
    unlock_condition:   { type: 'streak', value: 60 },
    dialogues: [
      { type: 'greeting',      text: 'Levanta-te e come, porque o caminho é longo para ti. 1 Reis 19:7' },
      { type: 'correct',       text: 'O fogo do Senhor caiu! Você acertou em cheio!' },
      { type: 'streak_broken', text: 'Eu também me deitei querendo desistir. E o anjo me tocou. Levante-se!' },
    ],
  },
  {
    name:               'Moisés',
    title:              'O Libertador',
    biblical_reference: 'Êxodo | Levítico | Números | Deuteronômio',
    biblical_story:     'Encontrado no Nilo, criado na corte do Faraó, chamado por Deus na sarça ardente. Liderou 2 milhões de pessoas para fora da escravidão, recebeu os Dez Mandamentos no Sinai e passou 40 anos conduzindo Israel.',
    sprite_url:         'https://placehold.co/200x280/2C3E50/white?text=MOISES',
    color_hex:          '#2C3E50',
    rarity:             'epic',
    is_sacred:          false,
    is_active:          true,
    sort_order:         8,
    unlock_condition:   { type: 'level', value: 35 },
    dialogues: [
      { type: 'greeting',  text: 'Quem sou eu para esta missão? — Mas Deus disse: EU SOU o que te envia.' },
      { type: 'correct',   text: 'Precisamente! Assim como Deus revelou Sua lei com clareza.' },
      { type: 'level_up',  text: 'Nível novo! Cada patamar é um novo monte Sinai a conquistar.' },
    ],
  },
  {
    name:               'Paulo',
    title:              'O Apóstolo dos Gentios',
    biblical_reference: 'Atos 9-28 | Romanos ao Filemom',
    biblical_story:     'Saulo de Tarso perseguia cristãos com fervor até encontrar Jesus ressurreto no caminho de Damasco. Tornou-se o maior missionário da história, fundou igrejas por todo o Mediterrâneo e escreveu 13 cartas do Novo Testamento.',
    sprite_url:         'https://placehold.co/200x280/8E44AD/white?text=PAULO',
    color_hex:          '#8E44AD',
    rarity:             'epic',
    is_sacred:          false,
    is_active:          true,
    sort_order:         9,
    unlock_condition:   { type: 'level', value: 35 },
    dialogues: [
      { type: 'greeting',        text: 'Tudo posso naquele que me fortalece. Vamos ao estudo!' },
      { type: 'correct',         text: 'Exato! Como disse a Timóteo: "Procura apresentar-te a Deus aprovado."' },
      { type: 'lesson_complete', text: 'Pelejei o bom combate desta lição, terminei a corrida. Bem feito!' },
    ],
  },
];
