export const SEED_MISSION_TEMPLATES = [
  // ═══════════════ MISSÕES DIÁRIAS — FÁCEIS ════════════════
  {
    title: 'Complete {target} lições hoje',
    description: '"A palavra de Deus é viva e eficaz." (Hb 4:12). Estude um pouquinho hoje!',
    icon_emoji: '📖',
    cycle: 'daily', trigger: 'lesson_count', target: 1,
    difficulty: 'easy', pf_reward: 10, mana_reward: 5,
    verse_reference: 'Hebreus 4:12',
    is_active: true, is_premium: false, weight: 10,
  },
  {
    title: 'Complete {target} lições hoje',
    description: 'Dois passos a mais na sua jornada de fé!',
    icon_emoji: '📚',
    cycle: 'daily', trigger: 'lesson_count', target: 2,
    difficulty: 'easy', pf_reward: 20, mana_reward: 8,
    is_active: true, is_premium: false, weight: 9,
  },
  {
    title: 'Ganhe {target} Pontos de Fé hoje',
    description: '"Tudo posso naquele que me fortalece." (Fp 4:13)',
    icon_emoji: '✨',
    cycle: 'daily', trigger: 'pf_earn', target: 20,
    difficulty: 'easy', pf_reward: 15, mana_reward: 5,
    verse_reference: 'Filipenses 4:13',
    is_active: true, is_premium: false, weight: 9,
  },
  {
    title: 'Mantenha seu streak ativo hoje',
    description: '"Seja constante na oração." (Rm 12:12). Não deixe a vela apagar!',
    icon_emoji: '🔥',
    cycle: 'daily', trigger: 'streak_maintain', target: 1,
    difficulty: 'easy', pf_reward: 15, mana_reward: 5,
    verse_reference: 'Romanos 12:12',
    is_active: true, is_premium: false, weight: 10,
  },

  // ═══════════════ MISSÕES DIÁRIAS — MÉDIAS ════════════════
  {
    title: 'Complete {target} lições hoje',
    description: 'Três lições — você está crescendo em fé e sabedoria!',
    icon_emoji: '🌟',
    cycle: 'daily', trigger: 'lesson_count', target: 3,
    difficulty: 'medium', pf_reward: 35, mana_reward: 12,
    is_active: true, is_premium: false, weight: 7,
  },
  {
    title: 'Acerte tudo em {target} lição(ões)',
    description: '"Aplica o teu coração ao ensino." (Pv 23:12). Foque e acerte!',
    icon_emoji: '💯',
    cycle: 'daily', trigger: 'perfect_lesson', target: 1,
    difficulty: 'medium', pf_reward: 30, mana_reward: 10,
    verse_reference: 'Provérbios 23:12',
    is_active: true, is_premium: false, weight: 7,
  },
  {
    title: 'Ganhe {target} Pontos de Fé hoje',
    description: 'Uma conquista sólida para o seu dia!',
    icon_emoji: '⚡',
    cycle: 'daily', trigger: 'pf_earn', target: 50,
    difficulty: 'medium', pf_reward: 25, mana_reward: 8,
    is_active: true, is_premium: false, weight: 7,
  },
  {
    title: 'Avance {target} lições em uma trilha',
    description: '"Firme os olhos em Jesus." (Hb 12:2). Foco na trilha!',
    icon_emoji: '🛤️',
    cycle: 'daily', trigger: 'trail_progress', target: 2,
    difficulty: 'medium', pf_reward: 30, mana_reward: 10,
    verse_reference: 'Hebreus 12:2',
    is_active: true, is_premium: false, weight: 6,
  },

  // ═══════════════ MISSÕES DIÁRIAS — DIFÍCEIS ════════════════
  {
    title: 'Complete {target} lições hoje',
    description: 'Cinco lições em um dia — você é um Apóstolo da disciplina!',
    icon_emoji: '🏆',
    cycle: 'daily', trigger: 'lesson_count', target: 5,
    difficulty: 'hard', pf_reward: 60, mana_reward: 20,
    is_active: true, is_premium: false, weight: 4,
  },
  {
    title: 'Acerte tudo em {target} lições seguidas',
    description: '"Feliz o homem que acha a sabedoria." (Pv 3:13). Perfeccionista!',
    icon_emoji: '👑',
    cycle: 'daily', trigger: 'perfect_lesson', target: 3,
    difficulty: 'hard', pf_reward: 70, mana_reward: 25,
    verse_reference: 'Provérbios 3:13',
    is_active: true, is_premium: true, weight: 3,
  },
  {
    title: 'Ganhe {target} Pontos de Fé hoje',
    description: 'Centena de Pontos de Fé em um único dia — extraordinário!',
    icon_emoji: '💎',
    cycle: 'daily', trigger: 'pf_earn', target: 100,
    difficulty: 'hard', pf_reward: 80, mana_reward: 30,
    is_active: true, is_premium: false, weight: 3,
  },

  // ═══════════════ MISSÕES SEMANAIS — FÁCEIS ════════════════
  {
    title: 'Complete {target} lições nesta semana',
    description: '"Os que esperam no Senhor renovarão as forças." (Is 40:31)',
    icon_emoji: '📅',
    cycle: 'weekly', trigger: 'lesson_count', target: 5,
    difficulty: 'easy', pf_reward: 40, mana_reward: 15,
    verse_reference: 'Isaías 40:31',
    is_active: true, is_premium: false, weight: 10,
  },
  {
    title: 'Mantenha {target} dias de streak esta semana',
    description: 'Cinco dias de devoção — mais da metade da semana na presença de Deus!',
    icon_emoji: '🕯️',
    cycle: 'weekly', trigger: 'streak_maintain', target: 5,
    difficulty: 'easy', pf_reward: 50, mana_reward: 18,
    is_active: true, is_premium: false, weight: 9,
  },
  {
    title: 'Ganhe {target} PF na liga esta semana',
    description: '"Pelejei o bom combate." (2Tm 4:7). Lute pela sua posição!',
    icon_emoji: '🥊',
    cycle: 'weekly', trigger: 'league_xp', target: 100,
    difficulty: 'easy', pf_reward: 45, mana_reward: 15,
    verse_reference: '2 Timóteo 4:7',
    is_active: true, is_premium: false, weight: 8,
  },

  // ═══════════════ MISSÕES SEMANAIS — MÉDIAS ════════════════
  {
    title: 'Complete {target} lições nesta semana',
    description: 'Dez passos na sua jornada. Você está crescendo!',
    icon_emoji: '⭐',
    cycle: 'weekly', trigger: 'lesson_count', target: 10,
    difficulty: 'medium', pf_reward: 80, mana_reward: 25,
    is_active: true, is_premium: false, weight: 7,
  },
  {
    title: 'Acerte tudo em {target} lições esta semana',
    description: '"Aproveita bem o tempo." (Ef 5:16). Qualidade, não só quantidade!',
    icon_emoji: '🎯',
    cycle: 'weekly', trigger: 'perfect_lesson', target: 5,
    difficulty: 'medium', pf_reward: 90, mana_reward: 30,
    verse_reference: 'Efésios 5:16',
    is_active: true, is_premium: false, weight: 6,
  },
  {
    title: 'Conclua {target} estudo bíblico esta semana',
    description: 'Um mergulho profundo na Palavra. Mais que uma lição!',
    icon_emoji: '🔍',
    cycle: 'weekly', trigger: 'study_complete', target: 1,
    difficulty: 'medium', pf_reward: 100, mana_reward: 35,
    is_active: true, is_premium: false, weight: 5,
  },
  {
    title: 'Mantenha a semana completa de streak ({target} dias)',
    description: '"Nunca se apague o vosso fervor." (Rm 12:11). A semana toda!',
    icon_emoji: '🔥',
    cycle: 'weekly', trigger: 'streak_maintain', target: 7,
    difficulty: 'medium', pf_reward: 120, mana_reward: 40,
    verse_reference: 'Romanos 12:11',
    is_active: true, is_premium: false, weight: 6,
  },

  // ═══════════════ MISSÕES SEMANAIS — DIFÍCEIS ════════════════
  {
    title: 'Complete {target} lições nesta semana',
    description: 'Vinte lições — você está entre os mais dedicados da jornada!',
    icon_emoji: '🏅',
    cycle: 'weekly', trigger: 'lesson_count', target: 20,
    difficulty: 'hard', pf_reward: 180, mana_reward: 60,
    is_active: true, is_premium: false, weight: 3,
  },
  {
    title: 'Convide {target} amigo(s) esta semana',
    description: '"Como são formosos os pés do que anuncia." (Rm 10:15). Compartilhe a fé!',
    icon_emoji: '📯',
    cycle: 'weekly', trigger: 'invite_friend', target: 1,
    difficulty: 'hard', pf_reward: 150, mana_reward: 50,
    verse_reference: 'Romanos 10:15',
    is_active: true, is_premium: false, weight: 2,
  },
];
