export const SEED_TRAILS = [
  // NUCLEO COMUM
  {
    title: 'Fundamentos: A Vida de Jesus',
    slug: 'fundamentos-vida-de-jesus',
    description: 'Percorra os principais momentos da vida de Jesus, do nascimento à ressurreição, através de lições envolventes e quizzes bíblicos.',
    order: 1, is_core: true, unlock_level: 1,
    estimated_hours: 6, is_premium: false, is_published: true,
    thumbnail_url: 'https://placehold.co/400x200/4A90E2/white?text=Vida+de+Jesus',
  },
  {
    title: 'As Raízes: Antigo Testamento Essencial',
    slug: 'raizes-antigo-testamento',
    description: 'Da criação ao exílio: conheça os fundamentos do Antigo Testamento, seus patriarcas, profetas e a aliança de Deus com Israel.',
    order: 2, is_core: true, unlock_level: 1,
    estimated_hours: 8, is_premium: false, is_published: true,
    thumbnail_url: 'https://placehold.co/400x200/D4A017/white?text=Antigo+Testamento',
  },
  {
    title: 'O Caminho do Amor: Os Ensinamentos',
    slug: 'caminho-do-amor',
    description: 'Aprofunde-se nos ensinamentos centrais de Jesus sobre amor, perdão, fé e oração.',
    order: 3, is_core: true, unlock_level: 3,
    estimated_hours: 4, is_premium: false, is_published: true,
    thumbnail_url: 'https://placehold.co/400x200/27AE60/white?text=Caminho+do+Amor',
  },
  {
    title: 'Sabedoria Viva: Salmos e Provérbios',
    slug: 'sabedoria-salmos-proverbios',
    description: 'Os livros poéticos da Bíblia ganham vida nesta trilha. Salmos de louvor, lamento e confiança.',
    order: 4, is_core: true, unlock_level: 5,
    estimated_hours: 5, is_premium: false, is_published: true,
    thumbnail_url: 'https://placehold.co/400x200/8E44AD/white?text=Sabedoria',
  },
  {
    title: 'Os Apóstolos: A Igreja Primitiva',
    slug: 'apostolos-igreja-primitiva',
    description: 'Atos dos Apóstolos e as cartas paulinas: como a Igreja nasceu e cresceu com fé inabalável.',
    order: 5, is_core: true, unlock_level: 8,
    estimated_hours: 7, is_premium: false, is_published: true,
    thumbnail_url: 'https://placehold.co/400x200/E67E22/white?text=Apostolos',
  },
  {
    title: 'Os Grandes Profetas',
    slug: 'grandes-profetas',
    description: 'Isaías, Jeremias, Ezequiel e Daniel: as vozes proféticas que anunciaram a vinda do Messias.',
    order: 6, is_core: true, unlock_level: 10,
    estimated_hours: 6, is_premium: false, is_published: true,
    thumbnail_url: 'https://placehold.co/400x200/1ABC9C/white?text=Profetas',
  },
  {
    title: 'Fé e Coragem: Histórias Heróicas',
    slug: 'fe-e-coragem',
    description: 'Davi e Golias, Ester e o rei, Daniel na cova dos leões. Histórias de fé radical.',
    order: 7, is_core: true, unlock_level: 12,
    estimated_hours: 4, is_premium: false, is_published: true,
    thumbnail_url: 'https://placehold.co/400x200/E74C3C/white?text=Fe+e+Coragem',
  },
  {
    title: 'O Sermão da Montanha',
    slug: 'sermao-da-montanha',
    description: 'O maior discurso da história humana em detalhes. As Bem-Aventuranças, o Pai-Nosso.',
    order: 8, is_core: true, unlock_level: 2,
    estimated_hours: 3, is_premium: false, is_published: true,
    thumbnail_url: 'https://placehold.co/400x200/3498DB/white?text=Sermao',
  },
  {
    title: 'As Parábolas de Jesus',
    slug: 'parabolas-de-jesus',
    description: 'O Filho Pródigo, o Bom Samaritano, os Talentos. Cada parábola revela o Reino de Deus.',
    order: 9, is_core: true, unlock_level: 4,
    estimated_hours: 4, is_premium: false, is_published: true,
    thumbnail_url: 'https://placehold.co/400x200/F39C12/white?text=Parabolas',
  },
  {
    title: 'O Apocalipse: Esperança e Vitória',
    slug: 'apocalipse-esperanca-vitoria',
    description: 'O último livro da Bíblia desmistificado. Simbologia, contexto histórico e esperança.',
    order: 10, is_core: true, unlock_level: 20,
    estimated_hours: 5, is_premium: true, is_published: true,
    thumbnail_url: 'https://placehold.co/400x200/2C3E50/white?text=Apocalipse',
  },
  // TRILHAS DE DENOMINACAO
  {
    title: 'Fundamentos Protestantes',
    slug: 'fundamentos-protestantes',
    description: 'Sola Scriptura, Sola Fide, Sola Gratia. A Reforma Protestante e seus pilares.',
    order: 11, is_core: false, denomination: 'Evangélico',
    unlock_level: 20, estimated_hours: 6,
    is_premium: false, is_published: true,
    thumbnail_url: 'https://placehold.co/400x200/2980B9/white?text=Protestantes',
  },
  {
    title: 'Fundamentos Católicos',
    slug: 'fundamentos-catolicos',
    description: 'Os Sacramentos, o Magistério da Igreja, a Tradição e o Catecismo.',
    order: 12, is_core: false, denomination: 'Católico',
    unlock_level: 20, estimated_hours: 7,
    is_premium: false, is_published: true,
    thumbnail_url: 'https://placehold.co/400x200/C0392B/white?text=Catolicos',
  },
  {
    title: 'O Evangelho Segundo o Espiritismo',
    slug: 'evangelhos-espiritismo',
    description: 'A visão espírita dos ensinamentos de Jesus. Caridade como centro.',
    order: 13, is_core: false, denomination: 'Espírita Cristão',
    unlock_level: 20, estimated_hours: 5,
    is_premium: false, is_published: true,
    thumbnail_url: 'https://placehold.co/400x200/16A085/white?text=Espiritismo',
  },
  {
    title: 'Graça e Predestinação',
    slug: 'graca-e-predestinacao',
    description: 'Calvinismo vs Arminianismo. Graça irresistível, livre-arbítrio e soberania de Deus.',
    order: 14, is_core: false, denomination: 'Protestante',
    unlock_level: 25, estimated_hours: 5,
    is_premium: true, is_published: true,
    thumbnail_url: 'https://placehold.co/400x200/8E44AD/white?text=Graca',
  },
  {
    title: 'Os Dons do Espírito Santo',
    slug: 'dons-espirito-santo',
    description: 'Glossolalia, cura, profecia e discernimento. Os dons espirituais na prática.',
    order: 15, is_core: false, denomination: 'Carismático',
    unlock_level: 15, estimated_hours: 4,
    is_premium: false, is_published: true,
    thumbnail_url: 'https://placehold.co/400x200/E74C3C/white?text=Dons',
  },
  // TRILHAS ESPECIAIS
  {
    title: 'A Bíblia em 40 Dias',
    slug: 'biblia-em-40-dias',
    description: 'Um panorama completo da Bíblia em 40 lições diárias. Do Gênesis ao Apocalipse.',
    order: 16, is_core: true, unlock_level: 1,
    estimated_hours: 10, is_premium: true, is_published: true,
    thumbnail_url: 'https://placehold.co/400x200/D4A017/white?text=40+Dias',
  },
  {
    title: 'Mulheres da Bíblia',
    slug: 'mulheres-da-biblia',
    description: 'Rute, Débora, Ester, Maria Madalena. Histórias de fé, coragem e transformação.',
    order: 17, is_core: true, unlock_level: 6,
    estimated_hours: 5, is_premium: false, is_published: true,
    thumbnail_url: 'https://placehold.co/400x200/E91E8C/white?text=Mulheres',
  },
  {
    title: 'Oração: Do Clamor à Intimidade',
    slug: 'oracao-do-clamor-a-intimidade',
    description: 'Modelos bíblicos de oração. Do clamor de Davi até a oração sacerdotal de Jesus.',
    order: 18, is_core: true, unlock_level: 8,
    estimated_hours: 4, is_premium: false, is_published: false,
    thumbnail_url: 'https://placehold.co/400x200/9B59B6/white?text=Oracao',
  },
  {
    title: 'Arqueologia Bíblica',
    slug: 'arqueologia-biblica',
    description: 'Evidências arqueológicas que contextualizam narrativas bíblicas. Ciência e fé em diálogo.',
    order: 19, is_core: true, unlock_level: 30,
    estimated_hours: 6, is_premium: true, is_published: false,
    thumbnail_url: 'https://placehold.co/400x200/795548/white?text=Arqueologia',
  },
  {
    title: 'O Dízimo e a Mordomia Cristã',
    slug: 'dizimo-mordomia-crista',
    description: 'O que a Bíblia ensina sobre dinheiro, generosidade e mordomia. Malaquias 3 e Lucas 21.',
    order: 20, is_core: true, unlock_level: 10,
    estimated_hours: 3, is_premium: false, is_published: false,
    thumbnail_url: 'https://placehold.co/400x200/F0B429/white?text=Dizimo',
  },
];
