export const SEED_BIBLE_STUDIES = [
  {
    title: 'As Bem-Aventuranças: A Vida que Deus Aprova',
    slug: 'bem-aventurancas',
    description: 'Descubra o que Jesus realmente quis dizer quando prometeu a felicidade verdadeira.',
    category: 'vida-crista', difficulty: 'beginner',
    is_premium: false, is_published: true, is_featured: true, order: 1,
    tags: ['sermão da montanha', 'felicidade', 'bem-aventuranças'],
    lessons: [
      {
        order: 0, title: 'Bem-aventurados os pobres em espírito',
        verse_ref: 'Mateus 5:3', verse_text: 'Bem-aventurados os pobres em espírito, porque deles é o reino dos céus.', verse_version: 'NVI',
        dialogue_intro: 'Olá! Hoje estamos no Monte das Bem-Aventuranças — Jesus está prestes a pronunciar as palavras mais revolucionárias da história sobre a verdadeira felicidade.',
        dialogue_character: 'Já ouvi muitas filosofias sobre felicidade, mas nenhuma como esta. Quando Jesus diz "pobre em espírito", ele não fala de depressão — fala de humildade radical diante de Deus!',
        dialogue_reaction: 'Exatamente! É como o rei mais poderoso que se prostra — não porque é fraco, mas porque reconhece algo maior. É força, não fraqueza.',
        dialogue_application: 'Hoje, antes de tomar uma decisão, pergunte a Deus primeiro. Não porque é obrigado — mas porque reconhece que Ele sabe mais. Isso é pobreza de espírito.',
        dialogue_dove_close: 'Incrível, né? A humildade não nos diminui — ela nos abre para o maior reino que existe. Você está crescendo na fé!',
        quiz_mc: { question: 'O que significa "pobre em espírito" em Mateus 5:3?', options: ['Ser socialmente humilde', 'Reconhecer dependência total de Deus', 'Não ter posses materiais', 'Sentir tristeza espiritual'], correct: 1 },
        quiz_fill: { verse_with_blank: 'Bem-aventurados os pobres em espírito, porque deles é o ___ dos céus.', answer: 'reino', hint: 'Começa com "r"' },
        quiz_order: { words: ['os', 'Bem-aventurados', 'em', 'pobres', 'espírito'], correct: ['Bem-aventurados', 'os', 'pobres', 'em', 'espírito'] },
        pf_reward: 20, mana_reward: 5,
      },
      {
        order: 1, title: 'Bem-aventurados os mansos',
        verse_ref: 'Mateus 5:5', verse_text: 'Bem-aventurados os mansos, porque herdarão a terra.', verse_version: 'NVI',
        dialogue_intro: 'Mansidão é fraqueza? O mundo acha que sim. Mas Jesus diz exatamente o oposto — e a história prova Ele certo.',
        dialogue_character: 'Davi era guerreiro e manso. Moisés era o mais manso homem da terra e guiou uma nação. Mansidão não é passividade — é poder com propósito.',
        dialogue_reaction: 'O grego usa praos — o cavalo treinado de guerra que obedece ao dono. Força total, sob controle. Isso é mansidão bíblica.',
        dialogue_application: 'Pense numa situação onde você reagiu com raiva recentemente. O que a mansidão faria diferente? Hoje pratique responder com calma intencional.',
        dialogue_dove_close: 'Manso herda a terra porque constrói ao invés de destruir. A mansidão é o poder mais subestimado do mundo.',
        quiz_mc: { question: 'Segundo Jesus, quem herdará a terra?', options: ['Os poderosos', 'Os ricos', 'Os mansos', 'Os sábios'], correct: 2 },
        quiz_fill: { verse_with_blank: 'Bem-aventurados os ___, porque herdarão a terra.', answer: 'mansos', hint: 'Antônimo de agressivo' },
        quiz_order: { words: ['a', 'mansos', 'os', 'herdarão', 'Bem-aventurados', 'terra'], correct: ['Bem-aventurados', 'os', 'mansos', 'herdarão', 'a', 'terra'] },
        pf_reward: 20, mana_reward: 5,
      },
    ],
  },
  {
    title: 'Davi: O Coração de Deus em Questão',
    slug: 'davi-coracao-de-deus',
    description: 'Pastor, guerreiro, rei, pecador, adorador. A vida de Davi é o espelho mais honesto da jornada de fé humana.',
    category: 'personagens', difficulty: 'intermediate',
    is_premium: true, is_published: true, is_featured: true, order: 2,
    tags: ['davi', 'adoração', 'arrependimento', 'liderança'],
    lessons: [
      {
        order: 0, title: 'O Pastor que Deus Escolheu',
        verse_ref: '1 Samuel 13:14', verse_text: 'O Senhor procurou para si um homem segundo o seu próprio coração.', verse_version: 'NVI',
        dialogue_intro: 'Imagine ser o filho mais novo, no campo com ovelhas, enquanto seus irmãos são apresentados ao profeta. Ninguém pensa em você. Mas Deus pensou.',
        dialogue_character: 'Sou Caleb — conheci guerreiros como Davi. O segredo dele não era a força física. Era que via Deus em tudo: nas ovelhas, nas estrelas, nos inimigos.',
        dialogue_reaction: 'Deus não escolhe pelos critérios humanos. Ele vê o coração — e investe em quem está disposto a buscá-Lo mesmo no anonimato do campo.',
        dialogue_application: 'Você está numa temporada invisível? Como Davi no campo, Deus está te formando agora mesmo. O que você pode adorar a Ele hoje, sem precisar de plateia?',
        dialogue_dove_close: 'A história de Davi começa no anonimato. A maior jornada de fé pode começar exatamente onde você está agora.',
        quiz_mc: { question: 'O que diferenciava Davi segundo 1 Samuel 13:14?', options: ['Força física extraordinária', 'Família de linhagem nobre', 'Coração disposto a buscar a Deus', 'Inteligência militar superior'], correct: 2 },
        quiz_fill: { verse_with_blank: 'O Senhor procurou para si um homem segundo o seu próprio ___.', answer: 'coração', hint: 'Centro da vida espiritual' },
        quiz_order: { words: ['Senhor', 'O', 'homem', 'para', 'procurou', 'si'], correct: ['O', 'Senhor', 'procurou', 'para', 'si', 'homem'] },
        pf_reward: 30, mana_reward: 10,
      },
      {
        order: 1, title: 'Cria em mim um coração puro',
        verse_ref: 'Salmos 51:10', verse_text: 'Cria em mim, ó Deus, um coração puro, e renova um espírito reto dentro de mim.', verse_version: 'NVI',
        dialogue_intro: 'Davi pecou gravemente — e o que ele fez? Não se escondeu. Não justificou. Escreveu o Salmo 51 — o maior poema de arrependimento da história.',
        dialogue_character: 'Esse salmo me arrepia. Davi não pede para Deus fingir que não aconteceu. Ele pede transformação total. "Cria em mim" — como se pedisse para ser refeito por dentro.',
        dialogue_reaction: 'O arrependimento bíblico não é só se sentir mal. É querer ser diferente. É pedir a Deus que faça o que você não consegue sozinho.',
        dialogue_application: 'Existe algo em você que você tenta consertar por força de vontade e não consegue? Experimente orar Salmos 51:10 literalmente.',
        dialogue_dove_close: 'Davi caiu. Mas levantou porque correu PARA Deus — não FUGIU de Deus. Esse é o segredo do homem segundo o coração de Deus.',
        quiz_mc: { question: 'O que Davi pede a Deus no Salmo 51:10?', options: ['Vingança dos inimigos', 'Coração puro e espírito reto', 'Prosperidade e paz', 'Força para combater'], correct: 1 },
        quiz_fill: { verse_with_blank: 'Cria em mim, ó Deus, um ___ puro, e renova um espírito reto dentro de mim.', answer: 'coração', hint: 'O que Deus buscou em Davi' },
        quiz_order: { words: ['mim', 'puro', 'Cria', 'Deus', 'em', 'coração', 'ó', 'um'], correct: ['Cria', 'em', 'mim', 'ó', 'Deus', 'um', 'coração', 'puro'] },
        pf_reward: 30, mana_reward: 10,
      },
    ],
  },
  {
    title: 'A Graça: O Dom que Você Não Merece',
    slug: 'graca-o-dom',
    description: 'O conceito mais radical do Evangelho: salvação não como prêmio pelo esforço, mas como presente.',
    category: 'doutrinas', difficulty: 'beginner',
    is_premium: true, is_published: true, is_featured: false, order: 3,
    tags: ['graça', 'salvação', 'efésios'],
    lessons: [{
      order: 0, title: 'Graça: não é o que você pensa',
      verse_ref: 'Efésios 2:8-9', verse_text: 'Porque pela graça vocês são salvos, por meio da fé — e isto não vem de vocês, é dom de Deus — não por obras, para que ninguém se glorie.', verse_version: 'NVI',
      dialogue_intro: 'Existe uma palavra grega que Paulo usa — kharis — que não tem equivalente perfeito em português. É favor imerecido.',
      dialogue_character: 'Cresci numa cultura onde tudo se ganha com esforço. A graça foi o conceito mais difícil da minha jornada. Por que Deus daria algo de graça?',
      dialogue_reaction: 'Porque nenhuma obra nossa poderia pagar a dívida do pecado. A graça não é barata — custou a Deus o próprio Filho.',
      dialogue_application: 'Como você trata sua relação com Deus? Tenta "merecer" o amor Dele? A graça nos liberta desse peso. Hoje você pode simplesmente receber.',
      dialogue_dove_close: 'A graça não é licença para pecar — é combustível para viver diferente. Você foi amado antes de merecer. Isso muda tudo.',
      quiz_mc: { question: 'Segundo Efésios 2:8-9, a salvação vem por meio de quê?', options: ['Obras boas', 'Rituais religiosos', 'Fé — como dom de Deus', 'Méritos próprios'], correct: 2 },
      quiz_fill: { verse_with_blank: 'Porque pela ___ vocês são salvos, por meio da fé.', answer: 'graça', hint: 'Favor imerecido de Deus' },
      quiz_order: { words: ['vocês', 'graça', 'pela', 'são', 'Porque', 'salvos'], correct: ['Porque', 'pela', 'graça', 'vocês', 'são', 'salvos'] },
      pf_reward: 25, mana_reward: 8,
    }],
  },
  {
    title: 'Ansiedade: O Que Jesus Disse Sobre Isso',
    slug: 'ansiedade-jesus',
    description: 'Mateus 6, Filipenses 4 e os Salmos falam diretamente ao coração ansioso.',
    category: 'vida-crista', difficulty: 'beginner',
    is_premium: true, is_published: true, is_featured: true, order: 4,
    tags: ['ansiedade', 'paz', 'filipenses', 'confiança'],
    lessons: [
      {
        order: 0, title: 'Não se preocupe — mas como?',
        verse_ref: 'Mateus 6:34', verse_text: 'Portanto, não se preocupem com o amanhã, pois o amanhã terá suas próprias preocupações. Basta a cada dia o seu próprio mal.', verse_version: 'NVI',
        dialogue_intro: 'Jesus disse isso num contexto em que as pessoas se preocupavam com comida e sobrevivência. Ele não ignorou a realidade. Ele a reencuadrou.',
        dialogue_character: 'Por muito tempo achei que fé significava não sentir ansiedade. Mas Jesus não diz "não sinta" — diz "não carregue o amanhã hoje".',
        dialogue_reaction: 'A ansiedade vive no futuro. A fé vive no presente. Jesus nos chama de volta para hoje — onde Ele está e onde a graça suficiente está disponível.',
        dialogue_application: 'Escreva três preocupações sobre o futuro. Entregue cada uma a Deus com uma frase curta. "Pai, eu te entrego isso." Isso é oração.',
        dialogue_dove_close: 'Viver um dia de cada vez não é fraqueza — é sabedoria. Deus já está amanhã. Você pode confiar que Ele cuida.',
        quiz_mc: { question: 'Qual é o foco do conselho de Jesus em Mateus 6:34?', options: ['Planejar bem o futuro', 'Não pensar em nada', 'Viver o presente sem o peso do amanhã', 'Ter fé para conseguir tudo'], correct: 2 },
        quiz_fill: { verse_with_blank: 'Portanto, não se preocupem com o ___, pois o amanhã terá suas próprias preocupações.', answer: 'amanhã', hint: 'O dia que vem depois de hoje' },
        quiz_order: { words: ['o', 'Portanto', 'com', 'preocupem', 'amanhã', 'não', 'se'], correct: ['Portanto', 'não', 'se', 'preocupem', 'com', 'o', 'amanhã'] },
        pf_reward: 25, mana_reward: 8,
      },
      {
        order: 1, title: 'A paz que excede todo entendimento',
        verse_ref: 'Filipenses 4:6-7', verse_text: 'Não andem ansiosos por coisa alguma, mas em tudo, pela oração e súplicas, e com ação de graças, apresentem seus pedidos a Deus.', verse_version: 'NVI',
        dialogue_intro: 'Paulo escreveu isso de dentro de uma prisão romana. Não estava em retiro espiritual — estava acorrentado. E ainda assim falava de paz.',
        dialogue_character: 'A paz que Paulo descreve não é ausência de problemas. É uma presença dentro dos problemas. Uma âncora no meio da tempestade.',
        dialogue_reaction: 'O caminho para essa paz é específico: oração + ação de graças. Não apenas pedir — mas agradecer enquanto pede.',
        dialogue_application: 'Tente hoje a oração de Filipenses: apresente um pedido, mas inclua uma coisa pela qual é grato. Veja se isso muda como você se sente.',
        dialogue_dove_close: 'A paz de Deus não é lógica — ela excede o entendimento. Mas ela é real, e está disponível para você agora mesmo.',
        quiz_mc: { question: 'Qual é o resultado prometido em Filipenses 4:7?', options: ['Riqueza e prosperidade', 'Solução imediata dos problemas', 'Paz que excede todo entendimento', 'Fim de todas as preocupações'], correct: 2 },
        quiz_fill: { verse_with_blank: 'E a ___ de Deus, que excede todo entendimento, guardará os seus corações.', answer: 'paz', hint: 'O que Jesus prometeu aos que O seguem' },
        quiz_order: { words: ['ansiosos', 'Não', 'alguma', 'por', 'andem', 'coisa'], correct: ['Não', 'andem', 'ansiosos', 'por', 'coisa', 'alguma'] },
        pf_reward: 30, mana_reward: 10,
      },
    ],
  },
  { title: 'O Evangelho de João: As 7 Declarações "Eu Sou"', slug: 'evangelho-joao-eu-sou', description: 'Jesus fez as afirmações mais ousadas da história. Um estudo das 7 declarações que definem Quem Ele é.', category: 'livros', difficulty: 'intermediate', is_premium: true, is_published: false, is_featured: false, order: 5, tags: ['joão', 'jesus', 'eu sou'], lessons: [] },
  { title: 'O Fruto do Espírito: Caráter Transformado', slug: 'fruto-do-espirito', description: 'Amor, alegria, paz, paciência... Não são conquistas — são resultados de uma vida conectada ao Espírito Santo.', category: 'vida-crista', difficulty: 'intermediate', is_premium: true, is_published: false, is_featured: false, order: 6, tags: ['espírito santo', 'caráter', 'gálatas'], lessons: [] },
  { title: 'O Pai Nosso: Aprendendo a Orar com Jesus', slug: 'pai-nosso-oracao', description: 'A oração mais conhecida do mundo é um modelo, não um script.', category: 'vida-crista', difficulty: 'beginner', is_premium: true, is_published: false, is_featured: false, order: 7, tags: ['oração', 'pai nosso', 'mateus'], lessons: [] },
  { title: 'Ressurreição: Por Que Isso Muda Tudo', slug: 'ressureicao-muda-tudo', description: 'Se Cristo não ressuscitou, nossa fé é inútil. O fato histórico mais importante e suas implicações práticas.', category: 'doutrinas', difficulty: 'intermediate', is_premium: true, is_published: false, is_featured: true, order: 8, tags: ['ressurreição', 'páscoa', 'coríntios'], lessons: [] },
  { title: 'O Sermão da Montanha: A Constituição do Reino', slug: 'sermao-da-montanha', description: 'Mateus 5–7 é o manifesto de Jesus sobre como o Reino de Deus funciona.', category: 'vida-crista', difficulty: 'advanced', is_premium: true, is_published: false, is_featured: false, order: 9, tags: ['sermão da montanha', 'mateus', 'reino'], lessons: [] },
  { title: 'Tiago: Fé com Mãos e Pés', slug: 'tiago-fe-com-maos', description: 'A carta mais prática do Novo Testamento. Fé sem obras é como um corpo sem espírito.', category: 'livros', difficulty: 'intermediate', is_premium: true, is_published: false, is_featured: false, order: 10, tags: ['tiago', 'obras', 'fé'], lessons: [] },
];
